### PR TITLE
Level1

### PR DESCRIPTION
**Pull request by Simpathey**
A first level for our frog to overcome! 

https://github.com/user-attachments/assets/a63cbb58-d757-429b-903a-341af6cac970

### CODE REVIEW

**Comment by Simpathey** [comment]
Only thing is this is tuned for max jump strength of 35 for big hop

**Comment by jonathandavidlewis** [comment]
Nice work making those little channels. I didn't even think about that. 

The main challenge I faced was trying to use little jumps to calibrate. It seemed I only had a very small area to hold the get a small jump, so I felt a little frustrated trying to reposition before a big jump.

**Comment by jonathandavidlewis** [comment]
@Simpathey Have you played with that? is that 1/2 the max mouse distance? If so, that's only 10 pixels from the frog to work with for a small jump.

**Review by jonathandavidlewis — APPROVED** [review]
Great work! TY.

**Pull request merged**
