### PR TITLE
add, well_background, edge_tileset, brick_edge, edge_tile_set tres

### LINKED ISSUE #27: create side wall tiles

### LINKED ISSUE #28: create background

### PR DESCRIPTION
**Pull request by Anticdope**
add imports, update master, platforn scene

add:
well_background
image

edge_tileset
image
build example
Animation2
collision layer for tileset
cap1
brick edge
image
full build example animation
Animation
full build static image
image

closes #27 
closes #28

### CODE REVIEW

**Comment by jonathandavidlewis** [comment]
Nice work on the tiles and the PR!

Are the changes to the aseprite master and frog_master.png intentional?
project/assets/art/frog_master.png

**Comment by Anticdope** [comment]
actually not sure why that png exists. it isnt actually used for anything. I went ahead and removed it. updates to frog_master.aseprite as intentional.

**Comment by jonathandavidlewis** [comment]
@Anticdope thanks. Can you rebase this with main? I notice this branch doesn't have the aseprite import update

**Comment by jonathandavidlewis** [comment]
That's the last thing, everything else looks great!

**Comment by Anticdope** [comment]
> That's the last thing, everything else looks great!

should be good now?

**Pull request merged**
